/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthenticatedRouteRouteImport } from './routes/(unauthenticated)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as unauthenticatedUpdatePasswordRouteImport } from './routes/(unauthenticated)/update-password'
import { Route as unauthenticatedResetPasswordRouteImport } from './routes/(unauthenticated)/reset-password'
import { Route as unauthenticatedRegisterRouteImport } from './routes/(unauthenticated)/register'
import { Route as unauthenticatedLoginRouteImport } from './routes/(unauthenticated)/login'
import { Route as authenticatedOrganizationSlugRouteRouteImport } from './routes/(authenticated)/$organizationSlug/route'
import { Route as authenticatedOrganizationSlugIndexRouteImport } from './routes/(authenticated)/$organizationSlug/index'
import { Route as authenticatedOrganizationSlugSettingsRouteImport } from './routes/(authenticated)/$organizationSlug/settings'
import { Route as authenticatedOrganizationSlugProfileRouteImport } from './routes/(authenticated)/$organizationSlug/profile'
import { Route as authenticatedOrganizationSlugApiRouteImport } from './routes/(authenticated)/$organizationSlug/api'
import { Route as authenticatedOrganizationSlugAuditLogsIndexRouteImport } from './routes/(authenticated)/$organizationSlug/audit-logs/index'
import { Route as authenticatedOrganizationSlugTTeamSlugRouteRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/route'
import { Route as authenticatedOrganizationSlugTTeamSlugIndexRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/index'
import { Route as authenticatedOrganizationSlugTTeamSlugQueuedSessionsRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/queued-sessions'
import { Route as authenticatedOrganizationSlugTTeamSlugProjectsRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/projects'
import { Route as authenticatedOrganizationSlugTTeamSlugDraftsRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/drafts'
import { Route as authenticatedOrganizationSlugTTeamSlugDevicesRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/devices'
import { Route as authenticatedOrganizationSlugTTeamSlugTerminalIndexRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/terminal/index'
import { Route as authenticatedOrganizationSlugTTeamSlugCommandsIndexRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/commands/index'
import { Route as authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/terminal/bookmarks'
import { Route as authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/terminal/$sessionId'
import { Route as authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/commands/$commandId'
import { Route as authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken'
import { Route as authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRouteImport } from './routes/(authenticated)/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording'

const unauthenticatedRouteRoute = unauthenticatedRouteRouteImport.update({
  id: '/(unauthenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const unauthenticatedUpdatePasswordRoute =
  unauthenticatedUpdatePasswordRouteImport.update({
    id: '/update-password',
    path: '/update-password',
    getParentRoute: () => unauthenticatedRouteRoute,
  } as any)
const unauthenticatedResetPasswordRoute =
  unauthenticatedResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => unauthenticatedRouteRoute,
  } as any)
const unauthenticatedRegisterRoute = unauthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const unauthenticatedLoginRoute = unauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const authenticatedOrganizationSlugRouteRoute =
  authenticatedOrganizationSlugRouteRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedOrganizationSlugIndexRoute =
  authenticatedOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugSettingsRoute =
  authenticatedOrganizationSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugProfileRoute =
  authenticatedOrganizationSlugProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugApiRoute =
  authenticatedOrganizationSlugApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugAuditLogsIndexRoute =
  authenticatedOrganizationSlugAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugRouteRoute =
  authenticatedOrganizationSlugTTeamSlugRouteRouteImport.update({
    id: '/t/$teamSlug',
    path: '/t/$teamSlug',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugIndexRoute =
  authenticatedOrganizationSlugTTeamSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugQueuedSessionsRoute =
  authenticatedOrganizationSlugTTeamSlugQueuedSessionsRouteImport.update({
    id: '/queued-sessions',
    path: '/queued-sessions',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugProjectsRoute =
  authenticatedOrganizationSlugTTeamSlugProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugDraftsRoute =
  authenticatedOrganizationSlugTTeamSlugDraftsRouteImport.update({
    id: '/drafts',
    path: '/drafts',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugDevicesRoute =
  authenticatedOrganizationSlugTTeamSlugDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugTerminalIndexRoute =
  authenticatedOrganizationSlugTTeamSlugTerminalIndexRouteImport.update({
    id: '/terminal/',
    path: '/terminal/',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugCommandsIndexRoute =
  authenticatedOrganizationSlugTTeamSlugCommandsIndexRouteImport.update({
    id: '/commands/',
    path: '/commands/',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRoute =
  authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRouteImport.update({
    id: '/terminal/bookmarks',
    path: '/terminal/bookmarks',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRoute =
  authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRouteImport.update({
    id: '/terminal/$sessionId',
    path: '/terminal/$sessionId',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRoute =
  authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRouteImport.update({
    id: '/commands/$commandId',
    path: '/commands/$commandId',
    getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRoute =
  authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRouteImport.update(
    {
      id: '/terminal/shared/$shareToken',
      path: '/terminal/shared/$shareToken',
      getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
    } as any,
  )
const authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRoute =
  authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRouteImport.update(
    {
      id: '/terminal/sessions/$sessionId/recording',
      path: '/terminal/sessions/$sessionId/recording',
      getParentRoute: () => authenticatedOrganizationSlugTTeamSlugRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexRoute
  '/$organizationSlug': typeof authenticatedOrganizationSlugRouteRouteWithChildren
  '/login': typeof unauthenticatedLoginRoute
  '/register': typeof unauthenticatedRegisterRoute
  '/reset-password': typeof unauthenticatedResetPasswordRoute
  '/update-password': typeof unauthenticatedUpdatePasswordRoute
  '/$organizationSlug/api': typeof authenticatedOrganizationSlugApiRoute
  '/$organizationSlug/profile': typeof authenticatedOrganizationSlugProfileRoute
  '/$organizationSlug/settings': typeof authenticatedOrganizationSlugSettingsRoute
  '/$organizationSlug/': typeof authenticatedOrganizationSlugIndexRoute
  '/$organizationSlug/t/$teamSlug': typeof authenticatedOrganizationSlugTTeamSlugRouteRouteWithChildren
  '/$organizationSlug/audit-logs': typeof authenticatedOrganizationSlugAuditLogsIndexRoute
  '/$organizationSlug/t/$teamSlug/devices': typeof authenticatedOrganizationSlugTTeamSlugDevicesRoute
  '/$organizationSlug/t/$teamSlug/drafts': typeof authenticatedOrganizationSlugTTeamSlugDraftsRoute
  '/$organizationSlug/t/$teamSlug/projects': typeof authenticatedOrganizationSlugTTeamSlugProjectsRoute
  '/$organizationSlug/t/$teamSlug/queued-sessions': typeof authenticatedOrganizationSlugTTeamSlugQueuedSessionsRoute
  '/$organizationSlug/t/$teamSlug/': typeof authenticatedOrganizationSlugTTeamSlugIndexRoute
  '/$organizationSlug/t/$teamSlug/commands/$commandId': typeof authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRoute
  '/$organizationSlug/t/$teamSlug/terminal/$sessionId': typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRoute
  '/$organizationSlug/t/$teamSlug/terminal/bookmarks': typeof authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRoute
  '/$organizationSlug/t/$teamSlug/commands': typeof authenticatedOrganizationSlugTTeamSlugCommandsIndexRoute
  '/$organizationSlug/t/$teamSlug/terminal': typeof authenticatedOrganizationSlugTTeamSlugTerminalIndexRoute
  '/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken': typeof authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRoute
  '/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording': typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedIndexRoute
  '/login': typeof unauthenticatedLoginRoute
  '/register': typeof unauthenticatedRegisterRoute
  '/reset-password': typeof unauthenticatedResetPasswordRoute
  '/update-password': typeof unauthenticatedUpdatePasswordRoute
  '/$organizationSlug/api': typeof authenticatedOrganizationSlugApiRoute
  '/$organizationSlug/profile': typeof authenticatedOrganizationSlugProfileRoute
  '/$organizationSlug/settings': typeof authenticatedOrganizationSlugSettingsRoute
  '/$organizationSlug': typeof authenticatedOrganizationSlugIndexRoute
  '/$organizationSlug/audit-logs': typeof authenticatedOrganizationSlugAuditLogsIndexRoute
  '/$organizationSlug/t/$teamSlug/devices': typeof authenticatedOrganizationSlugTTeamSlugDevicesRoute
  '/$organizationSlug/t/$teamSlug/drafts': typeof authenticatedOrganizationSlugTTeamSlugDraftsRoute
  '/$organizationSlug/t/$teamSlug/projects': typeof authenticatedOrganizationSlugTTeamSlugProjectsRoute
  '/$organizationSlug/t/$teamSlug/queued-sessions': typeof authenticatedOrganizationSlugTTeamSlugQueuedSessionsRoute
  '/$organizationSlug/t/$teamSlug': typeof authenticatedOrganizationSlugTTeamSlugIndexRoute
  '/$organizationSlug/t/$teamSlug/commands/$commandId': typeof authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRoute
  '/$organizationSlug/t/$teamSlug/terminal/$sessionId': typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRoute
  '/$organizationSlug/t/$teamSlug/terminal/bookmarks': typeof authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRoute
  '/$organizationSlug/t/$teamSlug/commands': typeof authenticatedOrganizationSlugTTeamSlugCommandsIndexRoute
  '/$organizationSlug/t/$teamSlug/terminal': typeof authenticatedOrganizationSlugTTeamSlugTerminalIndexRoute
  '/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken': typeof authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRoute
  '/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording': typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(unauthenticated)': typeof unauthenticatedRouteRouteWithChildren
  '/(authenticated)/$organizationSlug': typeof authenticatedOrganizationSlugRouteRouteWithChildren
  '/(unauthenticated)/login': typeof unauthenticatedLoginRoute
  '/(unauthenticated)/register': typeof unauthenticatedRegisterRoute
  '/(unauthenticated)/reset-password': typeof unauthenticatedResetPasswordRoute
  '/(unauthenticated)/update-password': typeof unauthenticatedUpdatePasswordRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/$organizationSlug/api': typeof authenticatedOrganizationSlugApiRoute
  '/(authenticated)/$organizationSlug/profile': typeof authenticatedOrganizationSlugProfileRoute
  '/(authenticated)/$organizationSlug/settings': typeof authenticatedOrganizationSlugSettingsRoute
  '/(authenticated)/$organizationSlug/': typeof authenticatedOrganizationSlugIndexRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug': typeof authenticatedOrganizationSlugTTeamSlugRouteRouteWithChildren
  '/(authenticated)/$organizationSlug/audit-logs/': typeof authenticatedOrganizationSlugAuditLogsIndexRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/devices': typeof authenticatedOrganizationSlugTTeamSlugDevicesRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/drafts': typeof authenticatedOrganizationSlugTTeamSlugDraftsRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/projects': typeof authenticatedOrganizationSlugTTeamSlugProjectsRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/queued-sessions': typeof authenticatedOrganizationSlugTTeamSlugQueuedSessionsRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/': typeof authenticatedOrganizationSlugTTeamSlugIndexRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/commands/$commandId': typeof authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/$sessionId': typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/bookmarks': typeof authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/commands/': typeof authenticatedOrganizationSlugTTeamSlugCommandsIndexRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/': typeof authenticatedOrganizationSlugTTeamSlugTerminalIndexRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken': typeof authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRoute
  '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording': typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/$organizationSlug/api'
    | '/$organizationSlug/profile'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/'
    | '/$organizationSlug/t/$teamSlug'
    | '/$organizationSlug/audit-logs'
    | '/$organizationSlug/t/$teamSlug/devices'
    | '/$organizationSlug/t/$teamSlug/drafts'
    | '/$organizationSlug/t/$teamSlug/projects'
    | '/$organizationSlug/t/$teamSlug/queued-sessions'
    | '/$organizationSlug/t/$teamSlug/'
    | '/$organizationSlug/t/$teamSlug/commands/$commandId'
    | '/$organizationSlug/t/$teamSlug/terminal/$sessionId'
    | '/$organizationSlug/t/$teamSlug/terminal/bookmarks'
    | '/$organizationSlug/t/$teamSlug/commands'
    | '/$organizationSlug/t/$teamSlug/terminal'
    | '/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken'
    | '/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/$organizationSlug/api'
    | '/$organizationSlug/profile'
    | '/$organizationSlug/settings'
    | '/$organizationSlug'
    | '/$organizationSlug/audit-logs'
    | '/$organizationSlug/t/$teamSlug/devices'
    | '/$organizationSlug/t/$teamSlug/drafts'
    | '/$organizationSlug/t/$teamSlug/projects'
    | '/$organizationSlug/t/$teamSlug/queued-sessions'
    | '/$organizationSlug/t/$teamSlug'
    | '/$organizationSlug/t/$teamSlug/commands/$commandId'
    | '/$organizationSlug/t/$teamSlug/terminal/$sessionId'
    | '/$organizationSlug/t/$teamSlug/terminal/bookmarks'
    | '/$organizationSlug/t/$teamSlug/commands'
    | '/$organizationSlug/t/$teamSlug/terminal'
    | '/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken'
    | '/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(unauthenticated)'
    | '/(authenticated)/$organizationSlug'
    | '/(unauthenticated)/login'
    | '/(unauthenticated)/register'
    | '/(unauthenticated)/reset-password'
    | '/(unauthenticated)/update-password'
    | '/(authenticated)/'
    | '/(authenticated)/$organizationSlug/api'
    | '/(authenticated)/$organizationSlug/profile'
    | '/(authenticated)/$organizationSlug/settings'
    | '/(authenticated)/$organizationSlug/'
    | '/(authenticated)/$organizationSlug/t/$teamSlug'
    | '/(authenticated)/$organizationSlug/audit-logs/'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/devices'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/drafts'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/projects'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/queued-sessions'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/commands/$commandId'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/$sessionId'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/bookmarks'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/commands/'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken'
    | '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  unauthenticatedRouteRoute: typeof unauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthenticated)': {
      id: '/(unauthenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof unauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(unauthenticated)/update-password': {
      id: '/(unauthenticated)/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof unauthenticatedUpdatePasswordRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(unauthenticated)/reset-password': {
      id: '/(unauthenticated)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof unauthenticatedResetPasswordRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(unauthenticated)/register': {
      id: '/(unauthenticated)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof unauthenticatedRegisterRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(unauthenticated)/login': {
      id: '/(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedLoginRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(authenticated)/$organizationSlug': {
      id: '/(authenticated)/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof authenticatedOrganizationSlugRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/$organizationSlug/': {
      id: '/(authenticated)/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof authenticatedOrganizationSlugIndexRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/settings': {
      id: '/(authenticated)/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/$organizationSlug/settings'
      preLoaderRoute: typeof authenticatedOrganizationSlugSettingsRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/profile': {
      id: '/(authenticated)/$organizationSlug/profile'
      path: '/profile'
      fullPath: '/$organizationSlug/profile'
      preLoaderRoute: typeof authenticatedOrganizationSlugProfileRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/api': {
      id: '/(authenticated)/$organizationSlug/api'
      path: '/api'
      fullPath: '/$organizationSlug/api'
      preLoaderRoute: typeof authenticatedOrganizationSlugApiRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/audit-logs/': {
      id: '/(authenticated)/$organizationSlug/audit-logs/'
      path: '/audit-logs'
      fullPath: '/$organizationSlug/audit-logs'
      preLoaderRoute: typeof authenticatedOrganizationSlugAuditLogsIndexRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug'
      path: '/t/$teamSlug'
      fullPath: '/$organizationSlug/t/$teamSlug'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/'
      path: '/'
      fullPath: '/$organizationSlug/t/$teamSlug/'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugIndexRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/queued-sessions': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/queued-sessions'
      path: '/queued-sessions'
      fullPath: '/$organizationSlug/t/$teamSlug/queued-sessions'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugQueuedSessionsRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/projects': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/projects'
      path: '/projects'
      fullPath: '/$organizationSlug/t/$teamSlug/projects'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugProjectsRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/drafts': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/drafts'
      path: '/drafts'
      fullPath: '/$organizationSlug/t/$teamSlug/drafts'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugDraftsRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/devices': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/devices'
      path: '/devices'
      fullPath: '/$organizationSlug/t/$teamSlug/devices'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugDevicesRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/'
      path: '/terminal'
      fullPath: '/$organizationSlug/t/$teamSlug/terminal'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalIndexRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/commands/': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/commands/'
      path: '/commands'
      fullPath: '/$organizationSlug/t/$teamSlug/commands'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugCommandsIndexRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/bookmarks': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/bookmarks'
      path: '/terminal/bookmarks'
      fullPath: '/$organizationSlug/t/$teamSlug/terminal/bookmarks'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/$sessionId': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/$sessionId'
      path: '/terminal/$sessionId'
      fullPath: '/$organizationSlug/t/$teamSlug/terminal/$sessionId'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/commands/$commandId': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/commands/$commandId'
      path: '/commands/$commandId'
      fullPath: '/$organizationSlug/t/$teamSlug/commands/$commandId'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken'
      path: '/terminal/shared/$shareToken'
      fullPath: '/$organizationSlug/t/$teamSlug/terminal/shared/$shareToken'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording': {
      id: '/(authenticated)/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording'
      path: '/terminal/sessions/$sessionId/recording'
      fullPath: '/$organizationSlug/t/$teamSlug/terminal/sessions/$sessionId/recording'
      preLoaderRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRouteImport
      parentRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRoute
    }
  }
}

interface authenticatedOrganizationSlugTTeamSlugRouteRouteChildren {
  authenticatedOrganizationSlugTTeamSlugDevicesRoute: typeof authenticatedOrganizationSlugTTeamSlugDevicesRoute
  authenticatedOrganizationSlugTTeamSlugDraftsRoute: typeof authenticatedOrganizationSlugTTeamSlugDraftsRoute
  authenticatedOrganizationSlugTTeamSlugProjectsRoute: typeof authenticatedOrganizationSlugTTeamSlugProjectsRoute
  authenticatedOrganizationSlugTTeamSlugQueuedSessionsRoute: typeof authenticatedOrganizationSlugTTeamSlugQueuedSessionsRoute
  authenticatedOrganizationSlugTTeamSlugIndexRoute: typeof authenticatedOrganizationSlugTTeamSlugIndexRoute
  authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRoute: typeof authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRoute
  authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRoute
  authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRoute
  authenticatedOrganizationSlugTTeamSlugCommandsIndexRoute: typeof authenticatedOrganizationSlugTTeamSlugCommandsIndexRoute
  authenticatedOrganizationSlugTTeamSlugTerminalIndexRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalIndexRoute
  authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRoute
  authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRoute: typeof authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRoute
}

const authenticatedOrganizationSlugTTeamSlugRouteRouteChildren: authenticatedOrganizationSlugTTeamSlugRouteRouteChildren =
  {
    authenticatedOrganizationSlugTTeamSlugDevicesRoute:
      authenticatedOrganizationSlugTTeamSlugDevicesRoute,
    authenticatedOrganizationSlugTTeamSlugDraftsRoute:
      authenticatedOrganizationSlugTTeamSlugDraftsRoute,
    authenticatedOrganizationSlugTTeamSlugProjectsRoute:
      authenticatedOrganizationSlugTTeamSlugProjectsRoute,
    authenticatedOrganizationSlugTTeamSlugQueuedSessionsRoute:
      authenticatedOrganizationSlugTTeamSlugQueuedSessionsRoute,
    authenticatedOrganizationSlugTTeamSlugIndexRoute:
      authenticatedOrganizationSlugTTeamSlugIndexRoute,
    authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRoute:
      authenticatedOrganizationSlugTTeamSlugCommandsCommandIdRoute,
    authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRoute:
      authenticatedOrganizationSlugTTeamSlugTerminalSessionIdRoute,
    authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRoute:
      authenticatedOrganizationSlugTTeamSlugTerminalBookmarksRoute,
    authenticatedOrganizationSlugTTeamSlugCommandsIndexRoute:
      authenticatedOrganizationSlugTTeamSlugCommandsIndexRoute,
    authenticatedOrganizationSlugTTeamSlugTerminalIndexRoute:
      authenticatedOrganizationSlugTTeamSlugTerminalIndexRoute,
    authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRoute:
      authenticatedOrganizationSlugTTeamSlugTerminalSharedShareTokenRoute,
    authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRoute:
      authenticatedOrganizationSlugTTeamSlugTerminalSessionsSessionIdRecordingRoute,
  }

const authenticatedOrganizationSlugTTeamSlugRouteRouteWithChildren =
  authenticatedOrganizationSlugTTeamSlugRouteRoute._addFileChildren(
    authenticatedOrganizationSlugTTeamSlugRouteRouteChildren,
  )

interface authenticatedOrganizationSlugRouteRouteChildren {
  authenticatedOrganizationSlugApiRoute: typeof authenticatedOrganizationSlugApiRoute
  authenticatedOrganizationSlugProfileRoute: typeof authenticatedOrganizationSlugProfileRoute
  authenticatedOrganizationSlugSettingsRoute: typeof authenticatedOrganizationSlugSettingsRoute
  authenticatedOrganizationSlugIndexRoute: typeof authenticatedOrganizationSlugIndexRoute
  authenticatedOrganizationSlugTTeamSlugRouteRoute: typeof authenticatedOrganizationSlugTTeamSlugRouteRouteWithChildren
  authenticatedOrganizationSlugAuditLogsIndexRoute: typeof authenticatedOrganizationSlugAuditLogsIndexRoute
}

const authenticatedOrganizationSlugRouteRouteChildren: authenticatedOrganizationSlugRouteRouteChildren =
  {
    authenticatedOrganizationSlugApiRoute:
      authenticatedOrganizationSlugApiRoute,
    authenticatedOrganizationSlugProfileRoute:
      authenticatedOrganizationSlugProfileRoute,
    authenticatedOrganizationSlugSettingsRoute:
      authenticatedOrganizationSlugSettingsRoute,
    authenticatedOrganizationSlugIndexRoute:
      authenticatedOrganizationSlugIndexRoute,
    authenticatedOrganizationSlugTTeamSlugRouteRoute:
      authenticatedOrganizationSlugTTeamSlugRouteRouteWithChildren,
    authenticatedOrganizationSlugAuditLogsIndexRoute:
      authenticatedOrganizationSlugAuditLogsIndexRoute,
  }

const authenticatedOrganizationSlugRouteRouteWithChildren =
  authenticatedOrganizationSlugRouteRoute._addFileChildren(
    authenticatedOrganizationSlugRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedOrganizationSlugRouteRoute: typeof authenticatedOrganizationSlugRouteRouteWithChildren
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedOrganizationSlugRouteRoute:
    authenticatedOrganizationSlugRouteRouteWithChildren,
  authenticatedIndexRoute: authenticatedIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface unauthenticatedRouteRouteChildren {
  unauthenticatedLoginRoute: typeof unauthenticatedLoginRoute
  unauthenticatedRegisterRoute: typeof unauthenticatedRegisterRoute
  unauthenticatedResetPasswordRoute: typeof unauthenticatedResetPasswordRoute
  unauthenticatedUpdatePasswordRoute: typeof unauthenticatedUpdatePasswordRoute
}

const unauthenticatedRouteRouteChildren: unauthenticatedRouteRouteChildren = {
  unauthenticatedLoginRoute: unauthenticatedLoginRoute,
  unauthenticatedRegisterRoute: unauthenticatedRegisterRoute,
  unauthenticatedResetPasswordRoute: unauthenticatedResetPasswordRoute,
  unauthenticatedUpdatePasswordRoute: unauthenticatedUpdatePasswordRoute,
}

const unauthenticatedRouteRouteWithChildren =
  unauthenticatedRouteRoute._addFileChildren(unauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  unauthenticatedRouteRoute: unauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
