/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthenticatedRouteRouteImport } from './routes/(unauthenticated)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as unauthenticatedUpdatePasswordRouteImport } from './routes/(unauthenticated)/update-password'
import { Route as unauthenticatedResetPasswordRouteImport } from './routes/(unauthenticated)/reset-password'
import { Route as unauthenticatedRegisterRouteImport } from './routes/(unauthenticated)/register'
import { Route as unauthenticatedLoginRouteImport } from './routes/(unauthenticated)/login'
import { Route as authenticatedOrganizationSlugRouteRouteImport } from './routes/(authenticated)/$organizationSlug/route'
import { Route as authenticatedOrganizationSlugIndexRouteImport } from './routes/(authenticated)/$organizationSlug/index'
import { Route as authenticatedOrganizationSlugSettingsRouteImport } from './routes/(authenticated)/$organizationSlug/settings'
import { Route as authenticatedOrganizationSlugQueuedSessionsRouteImport } from './routes/(authenticated)/$organizationSlug/queued-sessions'
import { Route as authenticatedOrganizationSlugProjectsRouteImport } from './routes/(authenticated)/$organizationSlug/projects'
import { Route as authenticatedOrganizationSlugDraftsRouteImport } from './routes/(authenticated)/$organizationSlug/drafts'
import { Route as authenticatedOrganizationSlugDevicesRouteImport } from './routes/(authenticated)/$organizationSlug/devices'
import { Route as authenticatedOrganizationSlugApiRouteImport } from './routes/(authenticated)/$organizationSlug/api'
import { Route as authenticatedOrganizationSlugCommandsIndexRouteImport } from './routes/(authenticated)/$organizationSlug/commands/index'
import { Route as authenticatedOrganizationSlugAuditLogsIndexRouteImport } from './routes/(authenticated)/$organizationSlug/audit-logs/index'
import { Route as authenticatedOrganizationSlugCommandsCommandIdRouteImport } from './routes/(authenticated)/$organizationSlug/commands/$commandId'

const unauthenticatedRouteRoute = unauthenticatedRouteRouteImport.update({
  id: '/(unauthenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const unauthenticatedUpdatePasswordRoute =
  unauthenticatedUpdatePasswordRouteImport.update({
    id: '/update-password',
    path: '/update-password',
    getParentRoute: () => unauthenticatedRouteRoute,
  } as any)
const unauthenticatedResetPasswordRoute =
  unauthenticatedResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => unauthenticatedRouteRoute,
  } as any)
const unauthenticatedRegisterRoute = unauthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const unauthenticatedLoginRoute = unauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const authenticatedOrganizationSlugRouteRoute =
  authenticatedOrganizationSlugRouteRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedOrganizationSlugIndexRoute =
  authenticatedOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugSettingsRoute =
  authenticatedOrganizationSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugQueuedSessionsRoute =
  authenticatedOrganizationSlugQueuedSessionsRouteImport.update({
    id: '/queued-sessions',
    path: '/queued-sessions',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugProjectsRoute =
  authenticatedOrganizationSlugProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugDraftsRoute =
  authenticatedOrganizationSlugDraftsRouteImport.update({
    id: '/drafts',
    path: '/drafts',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugDevicesRoute =
  authenticatedOrganizationSlugDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugApiRoute =
  authenticatedOrganizationSlugApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugCommandsIndexRoute =
  authenticatedOrganizationSlugCommandsIndexRouteImport.update({
    id: '/commands/',
    path: '/commands/',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugAuditLogsIndexRoute =
  authenticatedOrganizationSlugAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)
const authenticatedOrganizationSlugCommandsCommandIdRoute =
  authenticatedOrganizationSlugCommandsCommandIdRouteImport.update({
    id: '/commands/$commandId',
    path: '/commands/$commandId',
    getParentRoute: () => authenticatedOrganizationSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexRoute
  '/$organizationSlug': typeof authenticatedOrganizationSlugRouteRouteWithChildren
  '/login': typeof unauthenticatedLoginRoute
  '/register': typeof unauthenticatedRegisterRoute
  '/reset-password': typeof unauthenticatedResetPasswordRoute
  '/update-password': typeof unauthenticatedUpdatePasswordRoute
  '/$organizationSlug/api': typeof authenticatedOrganizationSlugApiRoute
  '/$organizationSlug/devices': typeof authenticatedOrganizationSlugDevicesRoute
  '/$organizationSlug/drafts': typeof authenticatedOrganizationSlugDraftsRoute
  '/$organizationSlug/projects': typeof authenticatedOrganizationSlugProjectsRoute
  '/$organizationSlug/queued-sessions': typeof authenticatedOrganizationSlugQueuedSessionsRoute
  '/$organizationSlug/settings': typeof authenticatedOrganizationSlugSettingsRoute
  '/$organizationSlug/': typeof authenticatedOrganizationSlugIndexRoute
  '/$organizationSlug/commands/$commandId': typeof authenticatedOrganizationSlugCommandsCommandIdRoute
  '/$organizationSlug/audit-logs': typeof authenticatedOrganizationSlugAuditLogsIndexRoute
  '/$organizationSlug/commands': typeof authenticatedOrganizationSlugCommandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedIndexRoute
  '/login': typeof unauthenticatedLoginRoute
  '/register': typeof unauthenticatedRegisterRoute
  '/reset-password': typeof unauthenticatedResetPasswordRoute
  '/update-password': typeof unauthenticatedUpdatePasswordRoute
  '/$organizationSlug/api': typeof authenticatedOrganizationSlugApiRoute
  '/$organizationSlug/devices': typeof authenticatedOrganizationSlugDevicesRoute
  '/$organizationSlug/drafts': typeof authenticatedOrganizationSlugDraftsRoute
  '/$organizationSlug/projects': typeof authenticatedOrganizationSlugProjectsRoute
  '/$organizationSlug/queued-sessions': typeof authenticatedOrganizationSlugQueuedSessionsRoute
  '/$organizationSlug/settings': typeof authenticatedOrganizationSlugSettingsRoute
  '/$organizationSlug': typeof authenticatedOrganizationSlugIndexRoute
  '/$organizationSlug/commands/$commandId': typeof authenticatedOrganizationSlugCommandsCommandIdRoute
  '/$organizationSlug/audit-logs': typeof authenticatedOrganizationSlugAuditLogsIndexRoute
  '/$organizationSlug/commands': typeof authenticatedOrganizationSlugCommandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(unauthenticated)': typeof unauthenticatedRouteRouteWithChildren
  '/(authenticated)/$organizationSlug': typeof authenticatedOrganizationSlugRouteRouteWithChildren
  '/(unauthenticated)/login': typeof unauthenticatedLoginRoute
  '/(unauthenticated)/register': typeof unauthenticatedRegisterRoute
  '/(unauthenticated)/reset-password': typeof unauthenticatedResetPasswordRoute
  '/(unauthenticated)/update-password': typeof unauthenticatedUpdatePasswordRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/$organizationSlug/api': typeof authenticatedOrganizationSlugApiRoute
  '/(authenticated)/$organizationSlug/devices': typeof authenticatedOrganizationSlugDevicesRoute
  '/(authenticated)/$organizationSlug/drafts': typeof authenticatedOrganizationSlugDraftsRoute
  '/(authenticated)/$organizationSlug/projects': typeof authenticatedOrganizationSlugProjectsRoute
  '/(authenticated)/$organizationSlug/queued-sessions': typeof authenticatedOrganizationSlugQueuedSessionsRoute
  '/(authenticated)/$organizationSlug/settings': typeof authenticatedOrganizationSlugSettingsRoute
  '/(authenticated)/$organizationSlug/': typeof authenticatedOrganizationSlugIndexRoute
  '/(authenticated)/$organizationSlug/commands/$commandId': typeof authenticatedOrganizationSlugCommandsCommandIdRoute
  '/(authenticated)/$organizationSlug/audit-logs/': typeof authenticatedOrganizationSlugAuditLogsIndexRoute
  '/(authenticated)/$organizationSlug/commands/': typeof authenticatedOrganizationSlugCommandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/$organizationSlug/api'
    | '/$organizationSlug/devices'
    | '/$organizationSlug/drafts'
    | '/$organizationSlug/projects'
    | '/$organizationSlug/queued-sessions'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/'
    | '/$organizationSlug/commands/$commandId'
    | '/$organizationSlug/audit-logs'
    | '/$organizationSlug/commands'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/update-password'
    | '/$organizationSlug/api'
    | '/$organizationSlug/devices'
    | '/$organizationSlug/drafts'
    | '/$organizationSlug/projects'
    | '/$organizationSlug/queued-sessions'
    | '/$organizationSlug/settings'
    | '/$organizationSlug'
    | '/$organizationSlug/commands/$commandId'
    | '/$organizationSlug/audit-logs'
    | '/$organizationSlug/commands'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(unauthenticated)'
    | '/(authenticated)/$organizationSlug'
    | '/(unauthenticated)/login'
    | '/(unauthenticated)/register'
    | '/(unauthenticated)/reset-password'
    | '/(unauthenticated)/update-password'
    | '/(authenticated)/'
    | '/(authenticated)/$organizationSlug/api'
    | '/(authenticated)/$organizationSlug/devices'
    | '/(authenticated)/$organizationSlug/drafts'
    | '/(authenticated)/$organizationSlug/projects'
    | '/(authenticated)/$organizationSlug/queued-sessions'
    | '/(authenticated)/$organizationSlug/settings'
    | '/(authenticated)/$organizationSlug/'
    | '/(authenticated)/$organizationSlug/commands/$commandId'
    | '/(authenticated)/$organizationSlug/audit-logs/'
    | '/(authenticated)/$organizationSlug/commands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  unauthenticatedRouteRoute: typeof unauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthenticated)': {
      id: '/(unauthenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof unauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(unauthenticated)/update-password': {
      id: '/(unauthenticated)/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof unauthenticatedUpdatePasswordRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(unauthenticated)/reset-password': {
      id: '/(unauthenticated)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof unauthenticatedResetPasswordRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(unauthenticated)/register': {
      id: '/(unauthenticated)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof unauthenticatedRegisterRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(unauthenticated)/login': {
      id: '/(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedLoginRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(authenticated)/$organizationSlug': {
      id: '/(authenticated)/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof authenticatedOrganizationSlugRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/$organizationSlug/': {
      id: '/(authenticated)/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof authenticatedOrganizationSlugIndexRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/settings': {
      id: '/(authenticated)/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/$organizationSlug/settings'
      preLoaderRoute: typeof authenticatedOrganizationSlugSettingsRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/queued-sessions': {
      id: '/(authenticated)/$organizationSlug/queued-sessions'
      path: '/queued-sessions'
      fullPath: '/$organizationSlug/queued-sessions'
      preLoaderRoute: typeof authenticatedOrganizationSlugQueuedSessionsRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/projects': {
      id: '/(authenticated)/$organizationSlug/projects'
      path: '/projects'
      fullPath: '/$organizationSlug/projects'
      preLoaderRoute: typeof authenticatedOrganizationSlugProjectsRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/drafts': {
      id: '/(authenticated)/$organizationSlug/drafts'
      path: '/drafts'
      fullPath: '/$organizationSlug/drafts'
      preLoaderRoute: typeof authenticatedOrganizationSlugDraftsRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/devices': {
      id: '/(authenticated)/$organizationSlug/devices'
      path: '/devices'
      fullPath: '/$organizationSlug/devices'
      preLoaderRoute: typeof authenticatedOrganizationSlugDevicesRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/api': {
      id: '/(authenticated)/$organizationSlug/api'
      path: '/api'
      fullPath: '/$organizationSlug/api'
      preLoaderRoute: typeof authenticatedOrganizationSlugApiRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/commands/': {
      id: '/(authenticated)/$organizationSlug/commands/'
      path: '/commands'
      fullPath: '/$organizationSlug/commands'
      preLoaderRoute: typeof authenticatedOrganizationSlugCommandsIndexRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/audit-logs/': {
      id: '/(authenticated)/$organizationSlug/audit-logs/'
      path: '/audit-logs'
      fullPath: '/$organizationSlug/audit-logs'
      preLoaderRoute: typeof authenticatedOrganizationSlugAuditLogsIndexRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
    '/(authenticated)/$organizationSlug/commands/$commandId': {
      id: '/(authenticated)/$organizationSlug/commands/$commandId'
      path: '/commands/$commandId'
      fullPath: '/$organizationSlug/commands/$commandId'
      preLoaderRoute: typeof authenticatedOrganizationSlugCommandsCommandIdRouteImport
      parentRoute: typeof authenticatedOrganizationSlugRouteRoute
    }
  }
}

interface authenticatedOrganizationSlugRouteRouteChildren {
  authenticatedOrganizationSlugApiRoute: typeof authenticatedOrganizationSlugApiRoute
  authenticatedOrganizationSlugDevicesRoute: typeof authenticatedOrganizationSlugDevicesRoute
  authenticatedOrganizationSlugDraftsRoute: typeof authenticatedOrganizationSlugDraftsRoute
  authenticatedOrganizationSlugProjectsRoute: typeof authenticatedOrganizationSlugProjectsRoute
  authenticatedOrganizationSlugQueuedSessionsRoute: typeof authenticatedOrganizationSlugQueuedSessionsRoute
  authenticatedOrganizationSlugSettingsRoute: typeof authenticatedOrganizationSlugSettingsRoute
  authenticatedOrganizationSlugIndexRoute: typeof authenticatedOrganizationSlugIndexRoute
  authenticatedOrganizationSlugCommandsCommandIdRoute: typeof authenticatedOrganizationSlugCommandsCommandIdRoute
  authenticatedOrganizationSlugAuditLogsIndexRoute: typeof authenticatedOrganizationSlugAuditLogsIndexRoute
  authenticatedOrganizationSlugCommandsIndexRoute: typeof authenticatedOrganizationSlugCommandsIndexRoute
}

const authenticatedOrganizationSlugRouteRouteChildren: authenticatedOrganizationSlugRouteRouteChildren =
  {
    authenticatedOrganizationSlugApiRoute:
      authenticatedOrganizationSlugApiRoute,
    authenticatedOrganizationSlugDevicesRoute:
      authenticatedOrganizationSlugDevicesRoute,
    authenticatedOrganizationSlugDraftsRoute:
      authenticatedOrganizationSlugDraftsRoute,
    authenticatedOrganizationSlugProjectsRoute:
      authenticatedOrganizationSlugProjectsRoute,
    authenticatedOrganizationSlugQueuedSessionsRoute:
      authenticatedOrganizationSlugQueuedSessionsRoute,
    authenticatedOrganizationSlugSettingsRoute:
      authenticatedOrganizationSlugSettingsRoute,
    authenticatedOrganizationSlugIndexRoute:
      authenticatedOrganizationSlugIndexRoute,
    authenticatedOrganizationSlugCommandsCommandIdRoute:
      authenticatedOrganizationSlugCommandsCommandIdRoute,
    authenticatedOrganizationSlugAuditLogsIndexRoute:
      authenticatedOrganizationSlugAuditLogsIndexRoute,
    authenticatedOrganizationSlugCommandsIndexRoute:
      authenticatedOrganizationSlugCommandsIndexRoute,
  }

const authenticatedOrganizationSlugRouteRouteWithChildren =
  authenticatedOrganizationSlugRouteRoute._addFileChildren(
    authenticatedOrganizationSlugRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedOrganizationSlugRouteRoute: typeof authenticatedOrganizationSlugRouteRouteWithChildren
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedOrganizationSlugRouteRoute:
    authenticatedOrganizationSlugRouteRouteWithChildren,
  authenticatedIndexRoute: authenticatedIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface unauthenticatedRouteRouteChildren {
  unauthenticatedLoginRoute: typeof unauthenticatedLoginRoute
  unauthenticatedRegisterRoute: typeof unauthenticatedRegisterRoute
  unauthenticatedResetPasswordRoute: typeof unauthenticatedResetPasswordRoute
  unauthenticatedUpdatePasswordRoute: typeof unauthenticatedUpdatePasswordRoute
}

const unauthenticatedRouteRouteChildren: unauthenticatedRouteRouteChildren = {
  unauthenticatedLoginRoute: unauthenticatedLoginRoute,
  unauthenticatedRegisterRoute: unauthenticatedRegisterRoute,
  unauthenticatedResetPasswordRoute: unauthenticatedResetPasswordRoute,
  unauthenticatedUpdatePasswordRoute: unauthenticatedUpdatePasswordRoute,
}

const unauthenticatedRouteRouteWithChildren =
  unauthenticatedRouteRoute._addFileChildren(unauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  unauthenticatedRouteRoute: unauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
